name: Project 1 - Manual CI

on:
  workflow_dispatch

jobs:
  run-basic-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 1-basics/p1-manual-ci   

    steps:
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 2 - Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Step 3 - Run JS File
        run: node index.js

      - name: Step 4 - Print Done
        run: echo "CI Completed ✅"