name: Project 2 - Auto CI

on:
  push:
    branches: ["main"]

jobs:
  run-auto-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 1-basics/p2-auto-ci   

    steps:
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 2 - Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Step 3 - Install Dependencies
        run: npm ci

      - name: Step 4 - Run App
        run: npm start

      - name: Step 5 - Done
        run: echo "Auto CI Completed ✅"