name: Project 2 - Auto CI

# on:
#   push:
#     branches: ["main"]
on:
  workflow_dispatch

jobs:
  run-auto-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 1-basics/p2-auto-ci

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run App
        run: node index.js

      - name: Done
        run: echo "Auto CI Completed ✅"