name: Project 8 - Env CI

on:
  push:
    branches: ["main"]

jobs:
  env-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 4-backend/p8-secrets-env

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Secret
        run: npm test
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}