name: Project 9 - Docker Build

# on:
#   push:
#     branches: ["main"]
on:
  workflow_dispatch

jobs:
  docker-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 5-docker/p9-dockerize

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t p9-app .